---
title: "PlusWord Analysis"
format:
  gfm:
    output-file: "README"
    output-ext:  "md"
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  warning: false
---

```{r constants}
library(tidyverse)
library(lubridate)

source("https://raw.githubusercontent.com/mattkwyatt/ggplot_themes/master/theme_mkw.R")

bar_colour <- "#20C2AA"

cbPalette <- c("#00BE73", "#56B4F9", "#FF79A7", "#EFCF00", "#0032B2", "#D55E00", "#7044D2")

times_filename <- "plusword_times.csv"
```

```{r data_processing}
df <- read_csv(str_c("../../Python/plusword/output/", times_filename), col_types = c("Tcc"))

df <- df |>
  mutate(time = str_c(rep("00:", length(df$time)), time),
         time = hms::parse_hms(time))

# Remove duplicates from slight date mismatches
df <- df |>
  mutate(date = date(date)) |>
  group_by(date, sender) |>
  summarise(time = min(time))

winning_times <- df |> 
  group_by(date(date)) |> 
  filter(time == min(time)) |> 
  ungroup()

start_date <- winning_times |> pull(date) |> min() |> date()
end_date <- winning_times |> pull(date) |> max() |> date()
```

## Overall Ranking

```{r ranking}
ranking <- df |>
  group_by(date(date)) |>
  mutate(rank = rank(time, ties.method = "min")) |>
  ungroup() |>
  group_by(sender, rank) |>
  summarise(rank_count = n()) |>
  pivot_wider(names_from = rank, values_from = rank_count, values_fill = 0) |>
  mutate(Games = rowSums(across(where(is.numeric)))) |>
  arrange(desc(`1`)) |> 
  rename(Player = sender)

knitr::kable(ranking)
```

```{r total_wins}
winning_times |> 
  group_by(sender) |> 
  summarise(wins = n()) |> 
  ungroup() |> 
  arrange(wins) |> 
  ggplot(aes(x = fct_reorder(sender, .x = wins, .fun = "max"), y = wins)) +
  geom_col(fill = bar_colour, colour = "black") +
  geom_text(aes(label = wins), nudge_y = 2) +
  scale_y_continuous(breaks = scales::pretty_breaks(),
                     expand = expansion(mult = c(0, 0.05))) +
  theme_mkw() +
  labs(x = "Player", y = "Victories",
       title = "PlusWord victories",
       subtitle = str_c(start_date, " to ", end_date))
```


```{r total_wins_over_time}
total_wins <- winning_times |> 
  group_by(date, sender) |> 
  summarise(wins = n()) |>
  ungroup() |> 
  group_by(sender) |> 
  mutate(total_wins = wins |> cumsum()) |> 
  select(-wins)

total_wins |> 
  rbind(tibble(sender = unique(total_wins$sender), date = min(total_wins$date)-1, total_wins = 0)) |> 
  rbind(total_wins |> group_by(sender) |> summarise(total_wins = max(total_wins)) |> mutate(date = now())) |> 
  ggplot(aes(x = date, y = total_wins, colour = sender)) +
  geom_step() +
  #geom_point()
  scale_y_continuous(breaks = scales::pretty_breaks(),
                     expand = expansion(mult = c(0, 0.05))) +
  theme_mkw() +
  labs(x = "Date", y = "Victories", colour = "Player",
       title = "PlusWord victories",
       subtitle = str_c(start_date, " to ", end_date))
```

Longest winning streaks for each player.

```{r win_streaks}
win_streaks <- winning_times |> 
  arrange(date) |> 
  pull(sender) |> 
  rle()

win_streaks <- tibble(sender = win_streaks$values, streak = win_streaks$lengths)

win_streaks |>
  group_by(sender) |>
  summarise(longest = max(streak)) |>
  arrange(desc(longest)) |> 
  knitr::kable(col.names = c("Player", "Longest streak"))
```

## Player Times

```{r time_boxplots}
median_time <- df |> group_by(sender) |> summarise(time = median(time))

df |>
  ggplot(aes(x = fct_reorder(sender, .x = time, .fun = "median"), y = time)) +
  geom_boxplot() +
  # geom_text(data = median_time, aes(label = time), nudge_y = 15, size = 3) +
  scale_y_time(labels = scales::time_format(format = "%M:%S"),
               limits = c(0, hms::hms(minutes = 10))) +
  theme_mkw(grid = TRUE) +
  labs(x = "Player", y = "Time (minutes)",
       title = "PlusWord finishing times (times over 10 minutes ignored)",
       subtitle = str_c(start_date, " to ", end_date))
```

```{r moving_average_time}
df |> 
  group_by(sender) |>
  mutate(rolling_mean = zoo::rollmean(time, k = 31, fill=NA)) |>
  ggplot(aes(x = date, colour = sender)) +
  geom_point(aes(y = time), alpha = 0.1) +
  geom_line(aes(y = rolling_mean)) +
  scale_y_time(labels = scales::time_format(format = "%M:%S"),
               limits = c(0, hms::hms(minutes = 5))) +
  theme_mkw() +
  labs(x = "Date", y = "Time (minutes)", colour = "Player",
       title = "Rolling mean PlusWord finishing times",
       subtitle = str_c(start_date, " to ", end_date))
```

```{r mean_time_delta, include=FALSE}
mean_times <- df |>
  group_by(date(date)) |>
  summarise(mean_time = mean(time)) |> 
  rename(date = `date(date)`)

df |> 
  mutate(date = date(date)) |> 
  left_join(mean_times, by = "date") |> 
  mutate(mean_time_delta = time - mean_time,
         pct_delta = as.numeric(mean_time_delta) / as.numeric(mean_time)) |>
  ggplot(aes(x = fct_reorder(sender, .x = pct_delta, .fun = "median"), y = pct_delta)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_boxplot() +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_mkw(grid = TRUE) +
  labs(x = "Player", y = "Percentage difference to mean time (%)",
       title = "PlusWord finishing times percentage difference to mean time",
       subtitle = str_c(start_date, " to ", end_date))
```

```{r fastest_time}
df |> 
  group_by(sender) |> 
  summarise(best_time = min(time)) |> 
  arrange(best_time) |> 
  ggplot(aes(x = fct_reorder(sender, .x = best_time), y = best_time)) +
  geom_col(fill = bar_colour, colour = "black") +
  geom_text(aes(label = best_time), nudge_y = 2) +
  scale_y_continuous(breaks = scales::pretty_breaks(),
                     expand = expansion(mult = c(0, 0.05))) +
  theme_mkw() +
  labs(x = "Player", y = "Time (seconds)",
       title = "Fastest PlusWord finishing time",
       subtitle = str_c(start_date, " to ", end_date))
```

```{r fastest_time_evolution}
df |> 
  mutate(record_time = as.numeric(df$time) |> cummin()) |> 
  filter(as.numeric(time) == record_time,
         time < hms::hms(minutes = 1)) |> 
  ggplot(aes(x = date, y = time)) +
  geom_step() +
  geom_segment(aes(x = max(date), y = min(time), xend = now(), yend = min(time))) +
  geom_point(aes(colour = sender), size = 5) +
  geom_point(data = df |> filter(time < 44),
             aes(colour = sender), alpha = 0.6, size = 3) +
  scale_y_continuous(breaks = scales::pretty_breaks()) +
  scale_colour_manual(values=cbPalette) +
  theme_mkw(grid = TRUE) +
  labs(x = "Date", y = "Time (seconds)", colour = "Player",
       title = "Record PlusWord finishing time",
       subtitle = str_c(start_date, " to ", end_date))
```

Ten fastest times overall.

```{r ten_fastest_times}
df |>
  mutate(date = date(date),
         time = as.numeric(time)) |>
  slice_min(order_by = time, n = 10) |> 
  mutate(rank = rank(time, ties.method = "min"), .before = date) |> 
  select(rank, sender, date, time) |> 
  knitr::kable(col.names = c("Rank", "Player", "Date", "Time (s)"))
```

## Time since last win

```{r days_since_last_win}
winning_times |>
  mutate(win_drought = max(date) - date) |>
  group_by(sender) |>
  summarise(win_drought = min(win_drought)) |>
  mutate(win_drought = round(as.numeric(win_drought, units = "days"), 0)) |>
  arrange(win_drought) |> 
  ggplot(aes(x = fct_reorder(sender, .x = win_drought), y = win_drought)) +
  geom_col(fill = bar_colour, colour = "black") +
  geom_text(aes(label = win_drought), nudge_y = 1) +
  scale_y_continuous(breaks = scales::pretty_breaks(),
                     expand = expansion(mult = c(0, 0.05))) +
  theme_mkw() +
  labs(x = "Player", y = "Time (days)",
       title = "Time since last PlusWord victory",
       subtitle = str_c(start_date, " to ", end_date))
```